  preCall: { label: "Pre-Call Prep", num: 1, maxPoints: 8 },
  discovery: { label: "Qualification", num: 2, maxPoints: 26 },
  presentation: { label: "Presentation", num: 3, maxPoints: 28 },
  pricing: { label: "Pricing & Objections", num: 4, maxPoints: 22 },
  closing: { label: "Close & Next Steps", num: 5, maxPoints: 16 },